from src.parser.WebParser import WebParser
from src.evaluator.BleuEvaluator import BleuEvaluator
from src.exceptions.WebParserException import WebParserException
from crawl4ai import DefaultMarkdownGenerator, AsyncWebCrawler, CrawlResult, BrowserConfig, CrawlerRunConfig, CacheMode
from bs4 import BeautifulSoup
import regex as re

class MarvelParser(WebParser):

    __SUPPORTED_DOMAIN: str = 'www.marvel.com'
    __TAG_EXCLUSIONS: list[str] = ['style', 'script', 'noscript', 'figure', 'meta', 'img', 'svg', 'iframe']
    __MARKDOWN_REGEX: str = r"##\s+(?:Gallery|Latest News|Buy Now|Posters|Featured Video|Big Game Trailer|Related Movie|Prepare|Teaser Trailer|Official Trailer|Final Trailer|Your Privacy Settings|Additional Links|.*?Will Return)"
    # Truncate after Overview section at the next boilerplate section heading

    __MARKDOWN_GEN_OPTIONS: dict[str, bool] = {
        'ignore_images': True,
        'escape_html': True,
        'ignore_links': False
    }

    __PAGE_LOAD: str = 'networkidle'
    __PAGE_TIMEOUT: int = 15000

    __CSS_EXCLUSIONS: str = '''
    nav, footer, header,
    .cookie-banner, .privacy-settings, .consent-popup,
    [class*="navigation"], [class*="footer"], [class*="header"],
    [class*="cookie"], [class*="consent"], [class*="privacy"],
    [class*="social-share"], [class*="newsletter"],
    [data-component="footer"], [data-component="header"]
    '''
    
    # lowest score obtained on all GS URL evaluations, we compare this with the strictest eval (BLEU) to check if we are using an outdated GS for an updated page
    __MIN_EVAL_SCORE: float = 1.0

    def __init__(self, gs_data: dict[str, list[dict]]):
        """
        Initializes the specific parser with domain-specific configurations.

        Overrides default web parsing settings with domain-specific targets, exclusions,
        and regex rules tailored to clean up the content from this specific domain. Also
        overrides the default browser configuration to bypass Marvel's anti-bot system.

        Args:
            gs_data (dict[str, list[dict]]): In-memory Gold Standard data used for fallback parsing.
        """
        super().__init__(
            targets = [],
            tag_excl = MarvelParser.__TAG_EXCLUSIONS,
            md_gen = DefaultMarkdownGenerator(options = MarvelParser.__MARKDOWN_GEN_OPTIONS),
            md_gen_opt = MarvelParser.__MARKDOWN_GEN_OPTIONS,
            css_excl = MarvelParser.__CSS_EXCLUSIONS,
            gs_data = gs_data
        )
        # Override browser config for Marvel's anti-bot protection
        self.browser_cfg: BrowserConfig = BrowserConfig(
            headless=True,
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            text_mode=True,
            enable_stealth=True # bypass anti-bot
        )
        # Update crawler config for Marvel parsing
        self.crawler_cfg.page_timeout = MarvelParser.__PAGE_TIMEOUT

    @classmethod
    def get_supported_domain(cls) -> str:
        return cls.__SUPPORTED_DOMAIN

    # Section labels that appear in the Overview area of Marvel movie pages
    __SECTION_LABELS: list[str] = [
        'Overview', 'Executive Producers', 'Executive Producer', 'Producers', 'Producer',
        'Co-Producer', 'Co-Producers', 'Screenplay by', 'Story by', 'Written by',
        'Directors', 'Director', 'Cast', 'Music By', 'Release Date'
    ]

    def __cleanup(self, md: str, title: str) -> str:
        """
        Cleans up the generated markdown text for Marvel movie pages.

        Gets the overview section from the raw markdown,
        formats section labels as markdown headings and prepends the movie title.
        
        Args:
            md (str): The raw markdown string generated by the crawler.
            title (str): The movie title to use as the h1 heading.

        Returns:
            str: The cleaned and sanitized markdown string.
        """
        # only overwiew section
        overview_match: re.Match[str] | None = re.search(r'(?:^|\n)Overview\s*\n', md, flags=re.IGNORECASE)
        if overview_match:
            md: str = md[overview_match.start():]
        
        end_match: re.Match[str] | None = re.search(MarvelParser.__MARKDOWN_REGEX, md, flags=re.IGNORECASE)
        if end_match:
            md: str = md[:end_match.start()]

        # to remove image
        md: str = re.sub(r'!\[.*?\]\(.*?\)\s*\n?', '', md)

        # for empty links
        md: str = re.sub(r'\[\]\(.*?\)\s*\n?', '', md)

        for label in MarvelParser.__SECTION_LABELS:
            md: str = re.sub(r'(?:^|\n)\s*' + re.escape(label) + r'\s*\n', f'\n## {label}\n', md)

        # insert movie title as h1 heading that i get from title tag truncated at |
        md: str = f"# {title}\n" + md.strip() + "\n"

        return md.strip()

    async def parse_url(self, url: str, **kwargs: any) -> dict[str, str]:
        """
        Crawls a Marvel.com movie page (or local HTML file), extracts content, and converts it to markdown.

        Args:
            Required:
                url (str): The Marvel URL to crawl and parse.
            Other:
                **kwargs: Keyword arguments, reserved for local parsing.

        Returns:
            dict[str, str]: A dictionary containing 'url', 'domain', 'title',
                'html_text', and the cleaned 'parsed_text'. Returns an empty dict if the crawl fails.

        Raises:
            WebParserException: If the internal fallback parse fails irrecoverably.
        """
        local_parse: bool = kwargs.get("local_parse", False)
        raw_html: str | None = kwargs.get("raw_html", None)

        self.crawler_cfg.magic = raw_html is None # disable human behaviour simulation if parse is local, speeds up parse
        self.crawler_cfg.wait_until = self._LOAD_DOM if raw_html else MarvelParser.__PAGE_LOAD
        self.browser_cfg.enable_stealth = raw_html is None # disable anti-bot bypass mode if parse is local, speeds up parse

        async with AsyncWebCrawler(config=self.browser_cfg) as crawler:
            if (url.count("/")) < 3:
                return {}
            
            domain: str = url.split('/')[2]
            html_text: None | str = None
            gs_text: None | str = None

            if domain in self.gs_data:
                for entry in self.gs_data[domain]:
                    if entry.get("url") == url:
                        html_text: str = entry.get("html_text")
                        gs_text: str = entry.get("gold_text")
                        break

            if (local_parse): 

                if domain not in self.gs_data:
                    raise WebParserException(f"[MarvelParser] Could not retrieve GS data for domain '{domain}'.")
                
                if not (html_text and gs_text):
                    raise WebParserException(f"[MarvelParser] Could not find GS for URL '{url}' during fallback local parse.")
                
            crawl_source: str = ""
            if (raw_html): crawl_source = f"raw:{raw_html}"
            elif (local_parse): crawl_source = f"raw:{html_text}"
            else: crawl_source = url
                                        
            result : CrawlResult = await crawler.arun(crawl_source, config = self.crawler_cfg)

            success: bool = result.success

            if not success or result.markdown.raw_markdown == '\n':
                return {}

            soup: BeautifulSoup = BeautifulSoup(result.html, 'html.parser')

            title_tag = soup.find('title')
            webpage_title: str = title_tag.get_text(strip=True) if title_tag else result.metadata.get("title", "Unknown title")
            movie_name: str = webpage_title.split('|')[0].strip() if '|' in webpage_title else webpage_title

            page_markdown: str = result.markdown.raw_markdown
            page_markdown = self.__cleanup(page_markdown, movie_name)
            body_length: int = len(page_markdown)

            if (self._DEBUG):
                print(f"[MarvelParser] Original HTML file length (in characters): {len(result.html)}")

            if (self._DEBUG):
                print(f"[MarvelParser] Successfully parsed webpage titled '{webpage_title}' for a total of {body_length} characters.")
                if self.md_gen_opt.get("ignore_links"):
                    print("[MarvelParser] | [WARNING] Links are currently being ignored!")
            
            if (not local_parse and not raw_html and gs_text and any(score < MarvelParser.__MIN_EVAL_SCORE for score in list(BleuEvaluator().evaluate(gs_text, page_markdown).model_dump().values()))):
                if (self._DEBUG):
                    print(f"[MarvelParser] | [WARNING] Computed preliminary evaluation score (BLEU) below minimum score for domain '{MarvelParser.__SUPPORTED_DOMAIN}' ({MarvelParser.__MIN_EVAL_SCORE}). The page (or article) may have been edited. Attempting fallback parse based on local GS data.")
                return await self.parse_url(url, local_parse=True, raw_html=None)

            extracted_html: str = result.html

            ret: dict[str, str] = {
                "url": url,
                "domain": domain,
                "title": webpage_title,
                "html_text": extracted_html,
                "parsed_text": page_markdown
            }

            return ret
