from src.parser.WebParser import WebParser
from src.exceptions.WebParserException import WebParserException
from src.evaluator.BleuEvaluator import BleuEvaluator
from crawl4ai import DefaultMarkdownGenerator, AsyncWebCrawler, CrawlResult
from bs4 import BeautifulSoup
import regex as re
class WikipediaParser(WebParser):

    __SUPPORTED_DOMAIN: str = 'it.wikipedia.org'
    __TAG_EXCLUSIONS: list[str] = ['style', 'script', 'noscript', 'figure', 'meta', 'img']
    __TARGETS: list[str] = ['.mw-parser-output']
    __MARKDOWN_REGEX: str = r"##\s+(?:See also|Notes|References|External links|Voci correlate|Note|Bibliografia|Collegamenti esterni|Altri progetti|Pagine correlate|Strumenti)" 
    # this is necessary since apparently some pages contain an arbitrary number of whitespaces between "##" and "Notes, References, etc."
    __CITE_NOTES_REGEX: str = r'\[\[[\w\s]+\]\]\(\s*https?://(?:[^()]|\([^()]*\))*\)|\[\[[\w\s]+\]\]\(#cite_note-[^)]+\)'

    __MARKDOWN_GEN_OPTIONS: dict[str, bool] = {
        'ignore_images': True, 
        'escape_html': True, 
        'ignore_links': False # we must include links in .md
    }

    __CSS_EXCLUSIONS: str = '''
    .infobox, .sinottico, .mw-editsection, .mw-references-wrap, .mw-references-columns, .CdA, .mw-empty-elt, .sinottico-divisione, .sinottico-testata,
    .hatnote, .avviso, .avviso-contenuto, .vedi-anche, .thumb, .mw-file-description, .mw-file-element, .navigation-not-searchable, .sinottico-testo-centrale,
    .col-begin[role="presentation"], .unsortable, .flagicon, .noviewer, .itwiki-template-da-Aiuto-a-Wikipedia, .itwiki-template-approfondimento-intestazione, .toc,
    .itwiki-template-approfondimento, .itwiki-template-approfondimento-destra, .avviso-disambigua, .avviso-mini, .avviso-mini-informazioni, .itwiki_template_toc,
    .box-Unreferenced_section, .ambox-Unreferenced, .gallery, .mw-gallery-traditional, .mw-indicator, .mw-highlight-copy-button, .ext-phonos-PhonosButton
    '''
    # NOTE: temporarily removed the following exclusions: .mw-collapsible, .mw-collapsed, .mw-made-collapsible, .noprint for performance improvement
    
    # lowest score obtained on all GS URL evaluations, we compare this with the strictest eval (BLEU) to check if we are using an outdated GS for an updated page
    __MIN_EVAL_SCORE: float = 0.965

    def __init__(self, gs_data: dict[str, list[dict]]):
        """
        Initializes the specific parser with domain-specific configurations.

        Overrides default web parsing settings with domain-specific targets, exclusions,
        and regex rules tailored to clean up the content from this specific domain.

        Args:
            gs_data (dict[str, list[dict]]): In-memory Gold Standard data used for local parsing.
        """
        super().__init__(
            targets = WikipediaParser.__TARGETS, 
            tag_excl = WikipediaParser.__TAG_EXCLUSIONS, 
            md_gen = DefaultMarkdownGenerator(options = WikipediaParser.__MARKDOWN_GEN_OPTIONS), 
            md_gen_opt = WikipediaParser.__MARKDOWN_GEN_OPTIONS,
            css_excl = WikipediaParser.__CSS_EXCLUSIONS,
            gs_data = gs_data
        )

    @classmethod
    def get_supported_domain(cls) -> str:
        return cls.__SUPPORTED_DOMAIN
    
    def __cleanup(self, md: str) -> str:
        """
        Cleans up the generated markdown text.

        Truncates the markdown before specific boilerplate sections (e.g., 'See also', 
        'Notes', 'References') and removes cite notes.

        Args:
            md (str): The raw markdown string generated by the crawler.

        Returns:
            str: The cleaned and sanitized markdown string.
        """
        re_match: re.Match[str] | None = re.search(WikipediaParser.__MARKDOWN_REGEX, md, flags=re.IGNORECASE)
        if (re_match):
            index_match: int = re_match.start()
            md: str = md[:index_match]

        md = re.sub(WikipediaParser.__CITE_NOTES_REGEX, ' ', md) # remove cite notes and cite note links 
        
        return md.strip()
    
    async def parse_url(self, url: str, **kwargs: any) -> dict[str, str]:
        """
        Crawls a Wikipedia webpage, extracts content, and converts it to markdown.

        Args:
            Required:
                url (str): The Wikipedia URL to crawl and parse.
            Other:
                **kwargs: Keyword arguments, reserved for local parsing.

        Returns:
            dict[str, str]: A dictionary containing 'url', 'domain', 'title', 
                'html_text', and the cleaned 'parsed_text'. Returns an empty dict if the crawl fails.

        Raises:
            WebParserException: If the internal fallback parse fails irrecoverably.
        """
        local_parse: bool = kwargs.get("local_parse", False)
        raw_html: str | None = kwargs.get("raw_html", None)

        async with AsyncWebCrawler(config=self.browser_cfg) as crawler:
        # Run the crawler on a URL
            if (url.count("/") < 3): # check for invalid URL "https://domain/page" is the bare minimum (so we need at least three slashes) 
                return {}
            
            domain: str = url.split('/')[2]
            html_text: None | str = None
            gs_text: None | str = None

            if domain in self.gs_data:
                for entry in self.gs_data[domain]:
                    if entry.get("url") == url:
                        html_text: str = entry.get("html_text")
                        gs_text: str = entry.get("gold_text")
                        break

            if (local_parse): 

                if domain not in self.gs_data:
                    raise WebParserException(f"[WikipediaParser] Could not retrieve GS data for domain '{domain}'.")
                
                if not (html_text and gs_text):
                    raise WebParserException(f"[WikipediaParser] Could not find GS for URL '{url}' during fallback local parse.")
                
            crawl_source: str = ""
            if (raw_html): crawl_source = f"raw:{raw_html}"
            elif (local_parse): crawl_source = f"raw:{html_text}"
            else: crawl_source = url    
                                        
            result : CrawlResult = await crawler.arun(crawl_source, config = self.crawler_cfg)

            success: bool = result.success

            if (not success or result.markdown.raw_markdown == '\n'): # check for empty results or crawling errors (URL not reachable, etc.)
                return {} # return empty dict on crawl failure

            soup: BeautifulSoup = BeautifulSoup(result.html, 'html.parser')
            h1_elem: BeautifulSoup._AtMostOneTag = soup.find('h1', id='firstHeading')
            title: str = h1_elem.get_text(strip=True) if h1_elem else 'Unknown title'
            webpage_title: str = result.metadata.get("title")

            page_markdown: str = f"# {title}\n" + result.markdown.raw_markdown # add title to extracted markdown
            page_markdown: str = self.__cleanup(page_markdown)
            body_length: int = len(page_markdown)

            if (self._DEBUG):
                print(f"[WikipediaParser] Original HTML file length (in characters): {len(result.html)}")

            if (self._DEBUG):
                print(f"[WikipediaParser] Successfully parsed webpage titled '{webpage_title}' for a total of {body_length} characters.")
                if (self.md_gen_opt.get("ignore_links")):
                    print("[WikipediaParser] | [WARNING] Links are currently being ignored! To change this behaviour, \
                          set 'ignore_links' in MARKDOWN_GEN_OPTIONS to False.")

            if (not local_parse and not raw_html and gs_text and any(score < WikipediaParser.__MIN_EVAL_SCORE for score in list(BleuEvaluator().evaluate(gs_text, page_markdown).model_dump().values()))):
                if (self._DEBUG):
                    print(f"[WikipediaParser] | [WARNING] Computed preliminary evaluation score (BLEU) below minimum \
                          score for domain '{WikipediaParser.__SUPPORTED_DOMAIN}' ({WikipediaParser.__MIN_EVAL_SCORE}). \
                            The page (or article) may have been edited. Attempting fallback parse based on local GS data.")
                    
                return await self.parse_url(url, local_parse=True, raw_html=None)

            extracted_html: str = result.html # original page HTML content

            ret: dict[str, str] = {
                "url": url,
                "domain": domain,
                "title": webpage_title,
                "html_text": extracted_html,
                "parsed_text": page_markdown
            }

            return ret