from src.parser.WebParser import WebParser
from src.exceptions.WebParserException import WebParserException
from src.evaluation.evaluation import bleu_eval
from crawl4ai import DefaultMarkdownGenerator, AsyncWebCrawler, CrawlResult
from bs4 import BeautifulSoup
import regex as re
import os
import json
class WikipediaParser(WebParser):

    __SUPPORTED_DOMAIN: str = 'it.wikipedia.org'
    __TAG_EXCLUSIONS: list[str] = ['style', 'script', 'noscript', 'figure', 'meta', 'img']
    __TARGETS: list[str] = ['.mw-parser-output']
    __MARKDOWN_REGEX: str = r"##\s+(?:See also|Notes|References|External links|Voci correlate|Note|Bibliografia|Collegamenti esterni|Altri progetti|Pagine correlate|Strumenti)" 
    # this is necessary since apparently some pages contain an arbitrary number of whitespaces between "##" and "Notes, References, etc."

    __MARKDOWN_GEN_OPTIONS: dict[str, bool] = {
        'ignore_images': True, 
        'escape_html': True, 
        'ignore_links': False # we must include links in .md
    }

    __CSS_EXCLUSIONS: str = '''
    .infobox, .sinottico, .mw-editsection, .mw-references-wrap, .mw-references-columns, .CdA, .mw-empty-elt, .sinottico-divisione, .sinottico-testata,
    .hatnote, .avviso, .avviso-contenuto, .vedi-anche, .thumb, .mw-file-description, .mw-file-element, .navigation-not-searchable, .sinottico-testo-centrale,
    .col-begin[role="presentation"], .unsortable, .flagicon, .noviewer, .itwiki-template-da-Aiuto-a-Wikipedia, .itwiki-template-approfondimento-intestazione, .toc,
    .itwiki-template-approfondimento, .itwiki-template-approfondimento-destra, .avviso-disambigua, .avviso-mini, .avviso-mini-informazioni, .itwiki_template_toc,
    .box-Unreferenced_section, .ambox-Unreferenced, .gallery, .mw-gallery-traditional, .mw-indicator, .mw-highlight-copy-button, .ext-phonos-PhonosButton
    '''
    # NOTE: temporarily removed the following exclusions: .mw-collapsible, .mw-collapsed, .mw-made-collapsible, .noprint for performance improvement
    
    # lowest score obtained on all GS URL evaluations, we compare this with the strictest eval (BLEU) to check if we are using an outdated GS for an updated page
    __MIN_EVAL_SCORE: float = 0.965
    __TMP_HTML_FPATH: str = "/tmp/local_wpp_tmp.html"

    def __init__(self):
        super().__init__(
            targets = WikipediaParser.__TARGETS, 
            tag_excl = WikipediaParser.__TAG_EXCLUSIONS, 
            md_gen = DefaultMarkdownGenerator(options = WikipediaParser.__MARKDOWN_GEN_OPTIONS), 
            md_gen_opt = WikipediaParser.__MARKDOWN_GEN_OPTIONS,
            css_excl= WikipediaParser.__CSS_EXCLUSIONS
        )

    @classmethod
    def get_supported_domain(cls) -> str:
        return cls.__SUPPORTED_DOMAIN
    
    def __cleanup(self, md: str) -> str:
        """
        Cleans up the generated markdown text.

        Truncates the markdown before specific boilerplate sections (e.g., 'See also', 
        'Notes', 'References') and sanitizes formatting using JSON serialization.

        Args:
            md (str): The raw markdown string generated by the crawler.

        Returns:
            str: The cleaned and sanitized markdown string.
        """
        re_match: re.Match[str] | None = re.search(WikipediaParser.__MARKDOWN_REGEX, md, flags=re.IGNORECASE)
        if (re_match):
            index_match: int = re_match.start()
            md: str = md[:index_match]
            
        return WebParser.json_seralize(md) 
    
    async def parse_url(self, url: str, **kwargs) -> dict[str, str]:
        """
        Crawls a Wikipedia webpage, extracts content, and converts it to markdown.

        Args:
            Required:
                url (str): The Wikipedia URL to crawl and parse.
            Other:
                **kwargs: Keyword arguments, reserved for internal fallback parsing, 
                          in case the page has changed since GS retrieval.

        Returns:
            dict[str, str]: A dictionary containing 'url', 'domain', 'title', 
                'html_text', and the cleaned 'parsed_text'. Returns an empty dict if the crawl fails.
        """
        local_parse: bool = kwargs.get("local_parse", False)

        async with AsyncWebCrawler(config=self.browser_cfg) as crawler:
        # Run the crawler on a URL
            if (url.count("/") < 3): # check for invalid URL "https://domain/page" is the bare minimum (so we need at least three slashes) 
                return {}
            
            domain: str = url.split('/')[2]
            gs_file_path: str = f"gs_data/" + domain.replace(".", "_") + "_gs.json"     # not src/ anymore for docker
            data: None = None
            html_data: None = None
            gs_data: None = None

            with open(file=gs_file_path, mode='r', encoding='UTF-8') as fin:
                data: list[dict] = json.load(fin)
                for entry in data:
                    if entry.get("url") == url:
                        html_data: str = entry.get("html_text")
                        gs_data: str = entry.get("gold_text")

            if (local_parse): # create tmp .html from GS data and crawl it
                if not os.path.exists(gs_file_path):
                    raise WebParserException(f"[WikipediaParser] Could not open file '{gs_file_path}'")

                with open(file=WikipediaParser.__TMP_HTML_FPATH, mode='w', encoding='UTF-8') as fout:
                    if (html_data):
                        fout.write(html_data)
                    else: 
                        raise WebParserException(f"[WikipediaParser] Could not find GS for URL '{url}' during fallback local parse.")
                                        
            result : CrawlResult = await crawler.arun(url if (not local_parse) else f"file://{WikipediaParser.__TMP_HTML_FPATH}", config = self.crawler_cfg)

            if (local_parse): # remove tmp .html file, since we no longer have any use for it
                if not os.path.exists(WikipediaParser.__TMP_HTML_FPATH):
                    raise WebParserException(f"[WikipediaParser] Could not remove file '{WikipediaParser.__TMP_HTML_FPATH}'")
                os.remove(WikipediaParser.__TMP_HTML_FPATH)

            success: bool = result.success

            if (not success or result.markdown.raw_markdown == '\n'): # check for empty results or crawling errors (URL not reachable, etc.)
                return {} # return empty dict on crawl failure

            soup: BeautifulSoup = BeautifulSoup(result.html, 'html.parser')
            h1_elem: BeautifulSoup._AtMostOneTag = soup.find('h1', id='firstHeading')
            title: str = h1_elem.get_text(strip=True) if h1_elem else 'Unknown title'
            webpage_title: str = result.metadata.get("title")

            page_markdown: str = f"# {title}\n" + result.markdown.raw_markdown # add title to extracted markdown
            page_markdown: str = self.__cleanup(page_markdown)
            body_length: int = len(page_markdown)

            if (WebParser.get_debug()):
                print(f"[WikipediaParser] Original HTML file length (in characters): {len(result.html)}")

            if (WebParser.get_debug()):
                print(f"[WikipediaParser] Successfully parsed webpage titled '{webpage_title}' for a total of {body_length} characters.")
                if (self.md_gen_opt.get("ignore_links")):
                    print("[WikipediaParser] | [WARNING] Links are currently being ignored! To change this behaviour, set 'ignore_links' in MARKDOWN_GEN_OPTIONS to False.")

            if (not local_parse and gs_data and any(score < WikipediaParser.__MIN_EVAL_SCORE for score in list(bleu_eval(gs_data, page_markdown).model_dump().values()))):
                if (WebParser.get_debug()):
                    print(f"[WikipediaParser] | [WARNING] Computed preliminary evaluation score (BLEU) below minimum score for domain '{WikipediaParser.__SUPPORTED_DOMAIN}' ({WikipediaParser.__MIN_EVAL_SCORE}). The page (or article) may have been edited. Attempting fallback parse based on local GS data.")
                return await self.parse_url(url, local_parse=True)

            raw_html: str = result.html # original page HTML content

            ret: dict[str, str] = {
                "url": url,
                "domain": domain,
                "title": webpage_title,
                "html_text": raw_html,
                "parsed_text": page_markdown
            }

            return ret