from src.parser.WebParser import WebParser
from crawl4ai import DefaultMarkdownGenerator, AsyncWebCrawler, CrawlResult
import regex as re
import json

class IpsosParser(WebParser):

    __SUPPORTED_DOMAIN: str = 'www.ipsos.com'
    __TAG_EXCLUSIONS: list[str] = ['style', 'script', 'noscript', 'figure', 'meta']
    __TARGETS: list[str] = ['.hero__title', '.hero__description', '.block-publications-content']
    __UNWANTED_HEADERS: list[str] = [r"Ipsos,\s+sondaggi\s+e\s+ricerche"]
    __MARKDOWN_REGEX: str = r"##\s+(?:\*\*|)\s*(?:" + "|".join(__UNWANTED_HEADERS) + r").*?[\s\S]*?(?=\n##|$)"
    __NEWSLETTER_REGEX: str = r"(^.*Newsletter.*$)"
    __PAGE_END_CONTACT_MESSAGES_EU = [
        r"Per\s+maggiori\s+informazioni",                   # IT
        r"Per\s+domande\s+dei\s+media",                     # IT
        r"For\s+more\s+information",                        # EN
        r"For\s+media\s+enquiries",                         # EN
        r"Für\s+Medienanfragen",                            # DE
        r"Für\s+weitere\s+Informationen",                   # DE
        r"Pour\s+plus\s+d'informations",                    # FR
        r"Pour\s+toute\s+demande\s+média",                  # FR
        r"Para\s+más\s+información",                        # ES
        r"Para\s+consultas\s+de\s+medios",                  # ES
        r"Для\s+получения\s+дополнительной\s+информации",   # RU
        r"Вопросы\s+для\s+СМИ"                              # RU
    ]

    __MAX_INTER_CHARS = 64
    __MIN_CONTACT_INFO_INDEX_LENGTH_RATIO = 0.6 # truncates the second part of the regex match if and only if we have read at least 60% of the page length 
    __CONTACT_REGEX = rf"(?:(?:-\s*){{3,}}|(?:\*\s*){{3,}}|(?:_\s*){{3,}})[\s\S]{{0,{__MAX_INTER_CHARS}}}?(?:" + "|".join(__PAGE_END_CONTACT_MESSAGES_EU) + r")[\s\S]*$"
    """
    We use this regex as a resort in attempting to remove contact information at the end of articles, if not inserted in a '.block-contact' or '.block-authors' div.
    Obviously, if the contact information is written in a slightly different manner, the parser is unable to remove the additional information, lowering
    the parse output quality. This might happen and is unavoidable. Common expressions for the most popular EU languages are used in the REGEX.
    """

    __MARKDOWN_GEN_OPTIONS: dict[str, bool] = {
        'ignore_images': True, 
        'escape_html': True, 
        'ignore_links': False # we must include links in .md
    }

    __CSS_EXCLUSIONS: str = '''.btn, .btn-cta, .contact-cards, .block-publications-list, .block-contact, .block-toolbar,
    .block-authors, .business-contact, .flourish-credit
    '''
    
    def __init__(self):
        super().__init__(
            targets = IpsosParser.__TARGETS, 
            tag_excl = IpsosParser.__TAG_EXCLUSIONS, 
            md_gen = DefaultMarkdownGenerator(options = IpsosParser.__MARKDOWN_GEN_OPTIONS), 
            md_gen_opt = IpsosParser.__MARKDOWN_GEN_OPTIONS,
            css_excl= IpsosParser.__CSS_EXCLUSIONS
        )

    @classmethod
    def get_supported_domain(cls) -> str:
        return cls.__SUPPORTED_DOMAIN
    
    def __cleanup(self, md: str) -> str:
        """
        Cleans up the generated markdown text.

        Truncates the markdown before specific boilerplate sections (e.g., 'Ipsos, sondaggi e ricerche', 
        article contact information for users and media, etc.) and sanitizes formatting using JSON serialization.

        Args:
            md (str): The raw markdown string generated by the crawler.

        Returns:
            str: The cleaned and sanitized markdown string.
        """
        original_len: int = len(md)
        
        re_match: re.Match[str] | None = re.search(IpsosParser.__CONTACT_REGEX, md, flags=re.IGNORECASE | re.MULTILINE)
        if (re_match):
            index_match: int = re_match.start()
            if (index_match > IpsosParser.__MIN_CONTACT_INFO_INDEX_LENGTH_RATIO * original_len):
                md: str = md[:index_match]

        re_match: re.Match[str] | None = re.search(IpsosParser.__MARKDOWN_REGEX, md, flags=re.IGNORECASE)
        if (re_match):
            index_match: int = re_match.start()
            md: str = md[:index_match]

        md = re.sub(IpsosParser.__NEWSLETTER_REGEX, "", md, flags=re.IGNORECASE | re.MULTILINE)
        # make these last lines a classmethod in WebParser? 
        md: str = json.dumps(md, ensure_ascii=False) # escape markdown string for JSON (also adds double quotes at the beginning and end of the string, which will be removed in the final output)
        if len(md) >= 2:
            md: str = md[1:-1] # remove double quotes from json.dumps()
        return md 
    
    async def parse_url(self, url: str) -> dict[str, str]:
        """
        Crawls a Wikipedia webpage, extracts content, and converts it to markdown.

        Args:
            url (str): The Wikipedia URL to crawl and parse.

        Returns:
            dict[str, str]: A dictionary containing 'url', 'domain', 'title', 
                'html_text', and the cleaned 'parsed_text'. Returns an empty dict if the crawl fails.
        """
        async with AsyncWebCrawler(config=self.browser_cfg) as crawler:
        # Run the crawler on a URL
            if (url.count("/") < 3): # check for invalid URL "https://domain/page" is the bare minimum (so we need at least three slashes) 
                return {}
                                        
            result : CrawlResult = await crawler.arun(url, config = self.crawler_cfg)

            success: bool = result.success

            if (not success or result.markdown.raw_markdown == '\n'): # check for empty results or crawling errors (URL not reachable, etc.)
                return {} # return empty dict on crawl failure

            webpage_title: str = result.metadata.get("title")

            page_markdown: str = result.markdown.raw_markdown # add title to extracted markdown
            page_markdown: str = self.__cleanup(page_markdown)
            body_length: int = len(page_markdown)

            if (WebParser.get_debug()):
                print(f"[IpsosParser] Original HTML file length (in characters): {len(result.html)}")

            if (WebParser.get_debug()):
                print(f"[IpsosParser] Successfully parsed webpage titled '{webpage_title}' for a total of {body_length} characters.")
                if (self.md_gen_opt.get("ignore_links")):
                    print("[IpsosParser] | [WARNING] Links are currently being ignored! To change this behaviour, set 'ignore_links' in MARKDOWN_GEN_OPTIONS to False.")

            raw_html: str = result.html # original page HTML content
            domain: str = url.split('/')[2]

            ret: dict[str, str] = {
                "url": url,
                "domain": domain,
                "title": webpage_title,
                "html_text": raw_html,
                "parsed_text": page_markdown
            }

            return ret