from src.parser.WebParser import WebParser
from crawl4ai import DefaultMarkdownGenerator, AsyncWebCrawler, CrawlResult, BrowserConfig, CrawlerRunConfig, CacheMode
from bs4 import BeautifulSoup
import regex as re
import json

class MarvelParser(WebParser):

    __SUPPORTED_DOMAIN: str = 'www.marvel.com'
    __TAG_EXCLUSIONS: list[str] = ['style', 'script', 'noscript', 'figure', 'meta', 'img', 'svg', 'iframe']
    __TARGETS: list[str] = []
    __MARKDOWN_REGEX: str = r"##\s+(?:Gallery|Latest News|Buy Now|Posters|Featured Video|Big Game Trailer|Related Movie|Prepare|Teaser Trailer|Official Trailer|Final Trailer|Your Privacy Settings|Additional Links|.*?Will Return)"
    # Truncate after Overview section at the next boilerplate section heading

    __MARKDOWN_GEN_OPTIONS: dict[str, bool] = {
        'ignore_images': True,
        'escape_html': True,
        'ignore_links': False
    }

    __CSS_EXCLUSIONS: str = '''
    nav, footer, header,
    .cookie-banner, .privacy-settings, .consent-popup,
    [class*="navigation"], [class*="footer"], [class*="header"],
    [class*="cookie"], [class*="consent"], [class*="privacy"],
    [class*="social-share"], [class*="newsletter"],
    [data-component="footer"], [data-component="header"]
    '''

    def __init__(self):
        # Override browser config for Marvel's anti-bot protection
        self.browser_cfg = BrowserConfig(
            headless=True,
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            text_mode=True,
        )
        self.md_gen_opt = MarvelParser.__MARKDOWN_GEN_OPTIONS
        self.crawler_cfg = CrawlerRunConfig(
            excluded_tags=MarvelParser.__TAG_EXCLUSIONS,
            markdown_generator=DefaultMarkdownGenerator(options=MarvelParser.__MARKDOWN_GEN_OPTIONS),
            excluded_selector=MarvelParser.__CSS_EXCLUSIONS,
            only_text=False,
            remove_forms=True,
            remove_consent_popups=False,
            word_count_threshold=10,
            cache_mode=CacheMode.BYPASS,
            wait_until='networkidle',
            page_timeout=30000,
            magic=True,
        )

    @classmethod
    def get_supported_domain(cls) -> str:
        return cls.__SUPPORTED_DOMAIN

    # Section labels that appear in the Overview area of Marvel movie pages
    __SECTION_LABELS: list[str] = [
        'Overview', 'Executive Producers', 'Executive Producer', 'Producers', 'Producer',
        'Co-Producer', 'Co-Producers', 'Screenplay by', 'Story by', 'Written by',
        'Directors', 'Director', 'Cast', 'Music By', 'Release Date'
    ]

    def __cleanup(self, md: str, title: str) -> str:
        """
        Cleans up the generated markdown text for Marvel movie pages.

        Gets the overview section from the raw markdown,
        formats section labels as markdown headings, prepends the movie title,
        and escapes for JSON compatibility (same convention as WikipediaParser).

        Args:
            md (str): The raw markdown string generated by the crawler.
            title (str): The movie title to use as the h1 heading.

        Returns:
            str: The cleaned and sanitized markdown string.
        """
        # only overwiew section
        overview_match = re.search(r'(?:^|\n)Overview\s*\n', md, flags=re.IGNORECASE)
        if overview_match:
            md = md[overview_match.start():]
        
        end_match = re.search(MarvelParser.__MARKDOWN_REGEX, md, flags=re.IGNORECASE)
        if end_match:
            md = md[:end_match.start()]

        # to remove image
        md = re.sub(r'!\[.*?\]\(.*?\)\s*\n?', '', md)

        # for empty links
        md = re.sub(r'\[\]\(.*?\)\s*\n?', '', md)

        for label in MarvelParser.__SECTION_LABELS:
            md = re.sub(r'(?:^|\n)\s*' + re.escape(label) + r'\s*\n', f'\n## {label}\n', md)

        # insert movie title as h1 heading that i get from title tag truncated at |
        md = f"# {title}\n" + md.strip() + "\n"
        md = json.dumps(md, ensure_ascii=False)
        if len(md) >= 2:
            md = md[1:-1]  # remove double quotes from json.dumps()

        return md

    async def parse_url(self, url: str) -> dict[str, str]:
        """
        Crawls a Marvel.com movie page, extracts content, and converts it to markdown.

        Args:
            url (str): The Marvel.com URL to crawl and parse.

        Returns:
            dict[str, str]: A dictionary containing 'url', 'domain', 'title',
                'html_text', and the cleaned 'parsed_text'. Returns an empty dict if the crawl fails.
        """
        async with AsyncWebCrawler(config=self.browser_cfg) as crawler:
            if url.count("/") < 3:
                return {}

            result: CrawlResult = await crawler.arun(url, config=self.crawler_cfg)

            success: bool = result.success

            if not success or result.markdown.raw_markdown == '\n':
                return {}

            soup: BeautifulSoup = BeautifulSoup(result.html, 'html.parser')

            title_tag = soup.find('title')
            webpage_title: str = title_tag.get_text(strip=True) if title_tag else result.metadata.get("title", "Unknown title")
            movie_name: str = webpage_title.split('|')[0].strip() if '|' in webpage_title else webpage_title

            page_markdown: str = result.markdown.raw_markdown
            page_markdown = self.__cleanup(page_markdown, movie_name)
            body_length: int = len(page_markdown)

            if WebParser.get_debug():
                print(f"[MarvelParser] Original HTML file length (in characters): {len(result.html)}")

            if WebParser.get_debug():
                print(f"[MarvelParser] Successfully parsed webpage titled '{webpage_title}' for a total of {body_length} characters.")
                if self.md_gen_opt.get("ignore_links"):
                    print("[MarvelParser] | [WARNING] Links are currently being ignored!")

            raw_html: str = result.html
            domain: str = url.split('/')[2]

            ret: dict[str, str] = {
                "url": url,
                "domain": domain,
                "title": webpage_title,
                "html_text": raw_html,
                "parsed_text": page_markdown
            }

            return ret
