services:
  backend:
    build: ./backend
    ports:
      - "8003:8003"
    image: minerva-web-parser
    volumes:
      - ./gs_data:/app/gs_data
      - ./domains.json:/app/domains.json
      - ./parser:/app/src/parser
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend